### ISSUE TITLE
Replace bg.mp4 video with the bg-mobile-fallback.jpg image

### ISSUE THREAD

**Issue by grabt03** [StartBootstrap/startbootstrap-coming-soon#42]
Hello!

Thank you for your awesome work.

I am a total newbie in coding and I would like to know if there is a way to force desktop web browsers to load the mobile fallback (.jpg image) instead of the .mp4 video in the background.

I have tried to replace this:
`  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="mp4/bg.mp4" type="video/mp4">
  </video>`

with this:
`<img src="img/bg-mobile-fallback.jpg" class="img-fluid">`

But the size of the image is not responding to the screen resolution (I use a custom image 1920x1080).

Any help is welcome!

**Comment by davidtmiller** [comment]
Remove the entire video element, and then remove the media query in the CSS surrounding the mobile fallback image. That will make the mobile fallback image show as the background image of the body element, and the video will be removed. Hopefully this helps!
